DROP DATABASE IF EXISTS BDPrestamo;
CREATE DATABASE BDPrestamo;

USE BDPrestamo;

CREATE TABLE CLIENTE(
  COD_CLI int auto_increment primary key,
  NOM_CLI varchar(50),
  APE_CLI varchar(50),
  DNI_CLI char(8)
);

INSERT INTO CLIENTE VALUES (NULL, 'JOSE', 'TIZNADO', '12345678');
INSERT INTO CLIENTE VALUES (NULL, 'LUIS', 'HUAMAN', '12345678');
INSERT INTO CLIENTE VALUES (NULL, 'PEDRO', 'MELGAREJO', '12345678');
INSERT INTO CLIENTE VALUES (NULL, 'MARIA', 'SOTO', '12345678');

SELECT * FROM CLIENTE;


DROP PROCEDURE IF EXISTS SP_BUSDEL_CLIENTE;
DELIMITER $$
CREATE PROCEDURE SP_BUSDEL_CLIENTE
(BUS VARCHAR(20), TIPO VARCHAR(3))
BEGIN
    IF TIPO='B' THEN
        SELECT * FROM CLIENTE WHERE COD_CLI=BUS OR NOM_CLI LIKE CONCAT('%',BUS,'%');
    ELSEIF TIPO='D' THEN
        DELETE FROM CLIENTE WHERE COD_CLI=BUS;
    END IF;
END $$
DELIMITER $$

CALL SP_BUSDEL_CLIENTE('','B');